"""Synthetic credit-card transaction generator (the fake "external acquirer").

Two hard requirements made this a real module instead of 20 lines of `random`:

1. **Reproducibility** — a seeded RNG.  You can rerun a demo, a test or a
   training job and get the same numbers.  (Also: fraud detection demos that
   change every run are impossible to debug.)

2. **Learnable fraud** — if `is_fraud` were a coin flip, the best model you
   could ever train is AUC 0.5 and this repo would be a lie.  So fraud is
   generated by *patterns* (burst velocity, card testing, abroad CNP, category
   switch, closed merchant), which are exactly the patterns the features in
   `jobs/common/features.py` describe.  The model then has real signal to find,
   and AUC ~0.9+ means the pipeline works.

Everything here is pure python (no Spark, no Kafka) so it can be unit-tested in
milliseconds and reused by both the streaming generator and the batch backfill.
"""
from __future__ import annotations

import math
import random
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone

COUNTRIES = ["US", "GB", "DE", "FR", "ES", "IT", "NL", "PL", "CA", "BR", "MX", "IN",
             "SG", "JP", "AU", "AE", "ZA", "TR", "SE", "NO", "CN", "KR"]
HIGH_RISK_COUNTRIES = ["BR", "MX", "IN", "NG", "VN", "PK", "BD", "RU", "UA", "CO"]

MERCHANT_CATEGORIES = [
    ("grocery", 45, 6, 0.01),
    ("fuel", 55, 8, 0.01),
    ("restaurant", 62, 10, 0.015),
    ("retail", 95, 25, 0.02),
    ("pharmacy", 35, 5, 0.01),
    ("travel", 480, 120, 0.03),
    ("electronics", 620, 200, 0.05),
    ("gambling", 340, 150, 0.11),
    ("crypto", 900, 400, 0.13),
    ("wire_transfer", 2200, 900, 0.16),
    ("digital_goods", 70, 30, 0.09),
    ("atm", 260, 90, 0.05),
]
CHANNELS = [("online", 0.52), ("pos", 0.40), ("atm", 0.08)]
SEGMENTS = ["consumer", "premium", "business", "student"]


def weighted_choice(rng: random.Random, options: list[tuple[str, float]]) -> str:
    total = sum(w for _, w in options)
    x = rng.random() * total
    acc = 0.0
    for name, w in options:
        acc += w
        if x <= acc:
            return name
    return options[-1][0]


def iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------- dimensions
def build_merchants(n: int = 120, rng: random.Random | None = None) -> list[dict]:
    rng = rng or random.Random(1)
    out = []
    for i in range(n):
        cat, mu, sigma, base_rate = rng.choice(MERCHANT_CATEGORIES)
        country = rng.choices(COUNTRIES + HIGH_RISK_COUNTRIES[:6],
                            weights=[3] * len(COUNTRIES) + [1] * 6, k=1)[0]
        risk = min(0.95, max(0.05, rng.gauss(base_rate * 6, 0.12)))
        if country in HIGH_RISK_COUNTRIES[:6]:
            risk = min(0.98, risk + 0.2)
        out.append({
            "merchant_id": f"MER-{i:04d}",
            "merchant_name": f"{cat.replace('_', ' ').title()} #{i:03d}",
            "merchant_category": cat,
            "merchant_country": country,
            "merchant_risk_score": round(risk, 4),
            "merchant_avg_ticket": round(max(5.0, rng.gauss(mu, sigma / 2)), 2),
            "merchant_first_seen": (date.today() - timedelta(days=rng.randint(30, 2000))).isoformat(),
            "merchant_closed": rng.random() < 0.04,
        })
    return out


def build_cards(n: int = 200, rng: random.Random | None = None) -> list[dict]:
    rng = rng or random.Random(2)
    out = []
    for i in range(n):
        segment = rng.choices(SEGMENTS, weights=[0.6, 0.15, 0.15, 0.1], k=1)[0]
        limit = {"consumer": 2500, "premium": 15000, "business": 40000, "student": 800}[segment]
        limit = round(max(300, rng.gauss(limit, limit * 0.3)), 2)
        out.append({
            "card_id": f"CARD-{i:05d}",
            "customer_id": f"CUST-{i // 2:05d}",
            "issuer_country": rng.choices(COUNTRIES, weights=[8 if c == "US" else 1 for c in COUNTRIES], k=1)[0],
            "credit_limit": limit,
            "txn_limit_1h": round(limit * rng.uniform(0.25, 0.6), 2),
            "travel_notice": rng.random() < 0.08,
            "card_age_days": rng.randint(10, 3000),
            "customer_segment": segment,
            "card_status": "active" if rng.random() > 0.03 else rng.choice(["blocked", "expired"]),
        })
    return out


# ------------------------------------------------------------------ simulator
@dataclass
class CardState:
    """Per-card memory so the generated stream contains real *patterns*."""
    card_id: str
    home_country: str
    credit_limit: float
    hourly_limit: float
    segment: str
    typical_amounts: dict[str, list[float]] = field(default_factory=dict)
    last_ts: datetime | None = None
    recent: list = field(default_factory=list)      # (ts, amount) of the last ~60 min
    used_merchants: set[str] = field(default_factory=set)
    home_merchants: list = field(default_factory=list)   # merchants located in the card's country
    burst_until: datetime | None = None
    abroad_until: datetime | None = None
    used_categories: set[str] = field(default_factory=set)
    rng: random.Random = None  # type: ignore[assignment]


class TransactionSimulator:
    """Yields `(transaction, label)` pairs, one event at a time.

    ``--fraud-rate`` steers how many events are *forced* into a fraud pattern;
    the rest can still turn fraudulent via their own base rate.
    """

    def __init__(self, merchants: Iterable[dict], cards: Iterable[dict], *,
                 seed: int = 1, fraud_rate: float = 0.05, label_noise: float = 0.06,
                 start: datetime | None = None,
                 end: datetime | None = None, rate_per_sec: float = 1.0):
        self.merchants = list(merchants)
        self.merchant_by_id = {m["merchant_id"]: m for m in self.merchants}
        self.cards = list(cards)
        self.rng = random.Random(seed)
        self.fraud_rate = fraud_rate
        self.label_noise = label_noise
        self.card_profiles = {c["card_id"]: c for c in self.cards}
        self.start = start or datetime.now(timezone.utc)
        self.end = end or (self.start + timedelta(days=1))
        self.rate_per_sec = max(0.001, rate_per_sec)
        # A card holder mostly shops at home: making the *merchant country*
        # depend on the card's issuer country is what turns "abroad" into a real
        # signal instead of background noise.
        self.issuer_of = {c["card_id"]: c["issuer_country"] for c in self.cards}
        self.merchants_by_country: dict[str, list[dict]] = {}
        for m in self.merchants:
            self.merchants_by_country.setdefault(m["merchant_country"], []).append(m)
        self.states = {
            c["card_id"]: CardState(
                card_id=c["card_id"], home_country=c["issuer_country"],
                credit_limit=c["credit_limit"], hourly_limit=c["txn_limit_1h"],
                segment=c["customer_segment"], rng=random.Random(f"{seed}:{c['card_id']}"),
                home_merchants=[m for m in self.merchants if m["merchant_country"] == c["issuer_country"]] or list(self.merchants),
            ) for c in self.cards
        }
        # each merchant has a "preferred" country for travel patterns
        for st in self.states.values():
            st.typical_amounts = {}

    # -- helpers ------------------------------------------------------------
    def _pick_merchant(self, st: CardState, fraud: str | None, abroad: bool = False) -> dict:
        """People mostly pay local merchants - which is what makes "abroad" a
        signal at all.  Fraud patterns deliberately break that habit."""
        rng = st.rng
        if fraud == "closed_merchant":
            pool = [m for m in self.merchants if m["merchant_closed"]] or self.merchants
            return rng.choice(pool)
        if fraud in ("abroad_cnp", "card_testing", "wire_drain"):
            pool = [m for m in self.merchants
                    if m["merchant_risk_score"] > 0.5 and m["merchant_country"] != st.home_country]
            if pool:
                return rng.choice(pool)
        if abroad or fraud in ("amount_spike", "atm_burst", "category_switch"):
            foreign = [m for m in self.merchants if m["merchant_country"] != st.home_country]
            if foreign:
                return rng.choice(foreign)
        local = st.home_merchants
        if local and rng.random() < 0.86:
            return rng.choice(local)
        return rng.choice(self.merchants)

    def _amount(self, st: CardState, merchant: dict, fraud: str | None) -> float:
        rng = st.rng
        cat = merchant["merchant_category"]
        base = merchant["merchant_avg_ticket"]
        if cat not in st.typical_amounts:
            st.typical_amounts[cat] = []
        hist = st.typical_amounts[cat]
        typical = sum(hist) / len(hist) if hist else base
        if fraud == "card_testing":
            return round(rng.uniform(0.3, 3.5), 2)
        if fraud in ("amount_spike", "abroad_cnp", "wire_drain"):
            mult = rng.uniform(4.0, 12.0)
        elif fraud == "atm_burst":
            mult = rng.uniform(1.6, 3.0)
        else:
            mult = min(1.9, max(0.3, rng.gauss(1.0, 0.35)))
        amount = max(0.5, min(45_000.0, typical * mult * rng.uniform(0.7, 1.5)))
        if fraud == "wire_drain":
            amount = max(amount, st.credit_limit * rng.uniform(0.7, 0.98))
        hist.append(amount)
        if len(hist) > 40:
            hist.pop(0)
        return round(amount, 2)

    def _next_ts(self, st: CardState) -> datetime:
        rng = st.rng
        if st.last_ts is None:
            ts = self.start + timedelta(seconds=rng.uniform(0, (self.end - self.start).total_seconds()))
        else:
            gap = rng.expovariate(self.rate_per_sec / max(1, len(self.states)))
            ts = st.last_ts + timedelta(seconds=min(gap, 36 * 3600))
        if ts > self.end:
            ts = self.end
        st.last_ts = ts
        return ts

    def _fraud_kind(self, st: CardState, now: datetime) -> str | None:
        """Force a pattern sometimes so the label is explainable, not random."""
        rng = st.rng
        if st.burst_until and now <= st.burst_until:
            return rng.choice(["atm_burst", "card_testing"])
        if st.abroad_until and now <= st.abroad_until:
            return "abroad_cnp"
        if rng.random() >= self.fraud_rate * 1.9:
            return None
        kind = rng.choices(
            ["burst_velocity", "card_testing", "amount_spike", "abroad_cnp",
             "category_switch", "wire_drain", "closed_merchant", "atm_burst"],
            weights=[0.18, 0.12, 0.14, 0.14, 0.10, 0.08, 0.08, 0.16], k=1)[0]
        if kind == "burst_velocity":
            st.burst_until = now + timedelta(minutes=rng.uniform(3, 12))
            return "card_testing" if rng.random() < 0.5 else "burst_velocity"
        if kind == "abroad_cnp":
            st.abroad_until = now + timedelta(hours=rng.uniform(4, 30))
        if kind == "closed_merchant":
            closed = [m for m in self.merchants if m["merchant_closed"]]
            if not closed:
                return None
        return kind

    # -- main --------------------------------------------------------------
    def one(self, card_id: str | None = None, now: datetime | None = None) -> tuple[dict, dict]:
        """Produce exactly one event (+ its ground-truth label)."""
        rng = self.rng
        st = self.states[card_id] if card_id else rng.choice(list(self.states.values()))
        ts = now or self._next_ts(st)
        fraud = self._fraud_kind(st, ts) if rng.random() < min(0.99, self.fraud_rate) else None

        on_holiday = self.card_profiles.get(st.card_id, {}).get("travel_notice", False)
        abroad = fraud in ("abroad_cnp", "wire_drain", "amount_spike", "atm_burst",
                           "category_switch") or (
            fraud is None and rng.random() < (0.28 if on_holiday else 0.035))

        merchant = self._pick_merchant(st, fraud, abroad=abroad)
        channel = ("online" if fraud in ("card_testing", "abroad_cnp", "category_switch")
                   else "atm" if fraud == "atm_burst"
                   else weighted_choice(rng, CHANNELS))
        if fraud == "card_testing":     # tiny authorisation tests at risky merchants
            merchant = rng.choice([m for m in self.merchants if m["merchant_risk_score"] > 0.5]
                                  or self.merchants)
        elif fraud == "category_switch":
            fresh = [m for m in self.merchants if m["merchant_category"] not in st.used_categories]
            merchant = rng.choice(fresh) if fresh else merchant
        amount = self._amount(st, merchant, fraud)

        home = st.home_country
        country = merchant["merchant_country"]
        if abroad and channel != "atm":
            foreign = [c for c in HIGH_RISK_COUNTRIES + ["JP", "SG", "AE", "TR", "ES", "IT"] if c != home]
            country = rng.choice(foreign or [home])
        elif country != home and rng.random() < 0.9:
            country = home               # a domestic card mostly pays domestic merchants

        st.used_categories.add(merchant["merchant_category"])
        st.used_merchants.add(merchant["merchant_id"])
        st.recent.append((ts, amount))
        st.recent = [(t, a) for t, a in st.recent if (ts - t) <= timedelta(minutes=60)][-200:]

        txn = {
            "transaction_id": f"TXN-{ts:%Y%m%d}-{rng.randrange(1 << 40):010x}",
            "event_ts": iso(ts),
            "event_ts_ts": ts,
            "card_id": st.card_id,
            "merchant_id": merchant["merchant_id"],
            "merchant_name": merchant["merchant_name"],
            "merchant_category": merchant["merchant_category"],
            "merchant_country": country,
            "amount": amount,
            "currency": "USD",
            "channel": channel,
            "card_present": channel in ("pos", "atm"),
            "is_3ds": channel == "online" and rng.random() < 0.6,
            "device_id": f"DEV-{rng.randrange(1 << 24):06x}",
            # the two fields below are the *simulator's* own memory of velocity.
            # The pipeline never reads them - features are computed from the data.
            # They only exist so risk_probability() can be honest about the label.
            "velocity_5min": sum(1 for t, _ in st.recent if (ts - t) <= timedelta(minutes=5)),
            "first_merchant_ever": merchant["merchant_id"] not in st.used_merchants,
            "_fraud_kind": fraud,
        }
        score, reasons = risk_probability(txn, merchant=merchant, card=st, fraud_kind=fraud)
        # A labelled event = "the dispute/chargeback file says fraud".  Injected
        # patterns are the primary source, then two deliberate imperfections so a
        # model cannot cheat by learning the generator:
        #   * some injected patterns are never reported (missed fraud)
        #   * some pattern-free events are disputed anyway (score > 0.30)
        if fraud is not None:
            label = 0 if st.rng.random() < self.label_noise else 1
        else:
            label = 1 if score > 0.30 else 0
        label_row = {
            "transaction_id": txn["transaction_id"],
            "label": label,
            "fraud_type": fraud or "base_rate_only",
            "score": round(score, 4),
            "reasons": reasons,
        }
        return txn, label_row


    def stream(self, n: int) -> Iterator[tuple[dict, dict]]:
        for _ in range(n):
            yield self.one()


# ------------------------------------------------------- the ground-truth rule
def risk_probability(txn: dict, merchant: dict, card: CardState | dict, fraud_kind: str | None) -> tuple[float, list[str]]:
    """Logistic combination of interpretable signals -> label probability.

    The same *idea* appears as hard rules in `jobs/common/rules.py`; here it is
    the noisy generator behind the labels.  Signals are deliberately imperfect
    (real fraud is not deterministic) so AUC lands in the realistic 0.85-0.95
    band instead of a fake 1.0.
    """
    rng = getattr(card, "rng", random.Random(0))
    # intercept = base rate.  Without it every "slightly odd" transaction looks
    # fraudulent; with it, a normal transaction sits around p=0.003.
    z = -5.2
    reasons: list[str] = []
    amount = float(txn["amount"])
    limit = float(getattr(card, "credit_limit", merchant.get("credit_limit", 2000)))
    hourly = float(getattr(card, "hourly_limit", 1500))

    if fraud_kind:
        z += {"card_testing": 4.4, "abroad_cnp": 3.9, "amount_spike": 3.6, "burst_velocity": 4.0,
              "category_switch": 3.1, "wire_drain": 3.8, "closed_merchant": 5.0, "atm_burst": 3.2
              }.get(fraud_kind, 2.5)
        reasons.append(f"pattern:{fraud_kind}")
    if amount / max(limit, 1) > 0.75:
        z += 1.0
        reasons.append("amount>75% of limit")
    if amount / max(hourly, 1) > 1.0:
        z += 1.2
        reasons.append("over hourly limit")
    if amount > 5000:
        z += 1.1
    risk = float(merchant.get("merchant_risk_score", 0.5))
    z += (risk - 0.45) * 1.8
    if risk > 0.75:
        reasons.append("high-risk merchant")
    if merchant.get("merchant_closed"):
        z += 4.0
        reasons.append("closed merchant")
    if txn["merchant_country"] != getattr(card, "home_country", None) and not txn["card_present"]:
        z += 1.5
        reasons.append("cnp abroad")
    elif txn["merchant_country"] != getattr(card, "home_country", None):
        z += 0.6
    if txn["channel"] == "online" and not txn["is_3ds"] and amount > 400:
        z += 0.7
        reasons.append("online >400 without 3DS")
    if amount < 4 and txn["channel"] == "online":
        z += 0.7
    if getattr(card, "segment", "") == "student" and amount > 800:
        z += 0.5
    if txn.get("velocity_5min", 0) >= 5:
        z += 1.4
        reasons.append(">=5 txns in 5 minutes")
    if txn.get("first_merchant_ever") and amount > 300:
        z += 0.8
        reasons.append("first-ever merchant at this size")
    z += rng.gauss(0, 0.9)            # irreducible noise (real fraud is not deterministic)
    p = 1.0 / (1.0 + math.exp(-z))
    return p, reasons


# --------------------------------------------------------------- public API
def generate_transactions(start: datetime, end: datetime, n: int, seed: int = 1,
                          fraud_rate: float = 0.05, label_noise: float = 0.06,
                          n_merchants: int = 120, n_cards: int = 200) -> tuple[list[dict], list[dict]]:
    """Deterministic history: returns (transactions, labels)."""
    rng = random.Random(seed)
    sim = TransactionSimulator(
        build_merchants(n_merchants, random.Random(seed + 1)),
        build_cards(n_cards, random.Random(seed + 2)),
        seed=seed, fraud_rate=fraud_rate, label_noise=label_noise, start=start, end=end,
        rate_per_sec=max(0.01, n / max(1.0, (end - start).total_seconds())),
    )
    # spread events over the window instead of chaining gaps from one card
    stamps = sorted(rng.uniform(start.timestamp(), end.timestamp()) for _ in range(n))
    txns, labels = [], []
    for ts in stamps:
        txn, label = sim.one(now=datetime.fromtimestamp(ts, tz=timezone.utc))
        txns.append(txn)
        labels.append(label)
    return txns, labels
